export const S = {
  title: 'ECHO',
  subtitle: '소리로 보는 던전',
  tapToStart: '탭하여 시작',
  normal: '일반 던전',
  daily: '오늘의 던전',
  records: '기록',
  ranking: '랭킹',
  settings: '설정',
  controls: '조작법',
  resume: '계속',
  toTitle: '타이틀로',
  toTitleConfirm: '진행 중인 탐험이 사라집니다. 타이틀로 돌아갈까요?',
  retry: '다시 도전',
  deeper: '더 깊이',
  close: '닫기',
  paused: '일시정지',
  died: '죽었습니다',
  escaped: '탈출 성공!',
  fellAt: (f: number) => `B${f}에서 쓰러졌습니다`,
  floorLabel: (f: number) => `B${f}`,
  locked: '잠겨 있습니다 — 열쇠가 필요합니다',
  keyTaken: '열쇠를 찾았습니다. 출구가 열립니다.',
  pickup: { stone: '돌멩이 획득', flare: '조명탄 획득', silencer: '소음기 획득', bandage: '붕대 획득' } as const,
  itemName: { stone: '돌멩이', flare: '조명탄', silencer: '소음기', bandage: '붕대' } as const,
  itemDesc: {
    stone: '던져서 적을 유인합니다 (마우스 방향)',
    flare: '주변을 넓고 오래 밝힙니다. 매우 시끄럽습니다',
    silencer: '12초 동안 발소리와 펄스 소음이 줄어듭니다',
    bandage: '체력을 1 회복합니다',
  } as const,
  itemFull: '더 들 수 없습니다',
  hpFull: '체력이 가득합니다',
  stats: { floor: '도달 층', time: '생존 시간', pulses: '펄스', stones: '던진 돌멩이', damage: '받은 피해', seen: '발견한 적', clear: '클리어 시간' },
  newBest: '최고 기록 갱신',
  newUnlocks: '새 해금',
  unlockName: {
    stone_start3: '돌멩이 3개로 시작',
    flare_start: '조명탄 1개로 시작',
    silencer_start: '소음기 1개로 시작',
    compass: '나침반 (가만히 서면 출구 방향)',
    heart4: '하트 4개',
    palette_alt: '호박색 팔레트',
  } as const,
  unlockHint: {
    stone_start3: '3층 도달',
    flare_start: '5층 도달',
    silencer_start: '7층 도달',
    compass: '8층 도달',
    heart4: '10층 클리어',
    palette_alt: '오늘의 던전 5층 도달',
  } as const,
  tutorial: {
    move: 'WASD / 방향키로 이동',
    pulse: 'Space 또는 클릭: 소나 펄스. 벽이 잠깐 보입니다',
    noise: '소리는 적을 부릅니다. Shift로 살금살금',
    stone: '1: 돌멩이를 던져 적을 유인하세요',
    heart: '심장 소리가 빨라지면 적이 가까이 있습니다',
    key: '열쇠를 찾아 출구를 여세요',
    listen: '출구는 낮게 웅웅거립니다. 귀를 기울이세요',
    moveTouch: '왼쪽 조이스틱으로 이동',
    pulseTouch: '오른쪽 버튼: 소나 펄스. 벽이 잠깐 보입니다',
    noiseTouch: '소리는 적을 부릅니다. 조이스틱을 살짝 밀면 살금살금',
    stoneTouch: '돌멩이 버튼으로 적을 유인하세요',
  },
  settingsLabels: { volume: '효과음 볼륨', shake: '화면 흔들림', touch: '터치 컨트롤', palette: '팔레트', touchAuto: '자동', touchOn: '켬', touchOff: '끔', paletteDefault: '기본', paletteAlt: '호박색', nickname: '닉네임 (랭킹)' },
  controlsText: [
    ['이동', 'W A S D / 방향키'],
    ['살금살금', 'Shift (소리 거의 없음, 느림)'],
    ['소나 펄스', 'Space / 마우스 왼쪽'],
    ['돌멩이 던지기', '1 / 마우스 오른쪽 (마우스 방향)'],
    ['조명탄 · 소음기 · 붕대', '2 · 3 · 4'],
    ['일시정지', 'Esc'],
  ],
  recordsLabels: { bestFloor: '최고 층', bestTime: '최단 클리어', runs: '탐험 횟수', dailyList: '오늘의 던전 기록', none: '기록 없음' },
  rank: {
    title: '랭킹',
    floorBoard: '최고 층',
    timeBoard: '최단 탈출',
    dailyBoard: '오늘의 던전',
    loading: '불러오는 중…',
    empty: '아직 기록이 없습니다. 첫 번째가 되어 보세요.',
    offline: '랭킹 서버에 연결할 수 없습니다',
    you: '나',
    submitted: '랭킹에 기록했습니다',
    namePrompt: '랭킹에 표시할 닉네임 (2~12자)',
    nameSave: '저장',
    skip: '건너뛰기',
    rankOf: (r: number) => `${r}위`,
  },
  win: '10층을 돌파해 지상으로 나왔습니다. 더 깊이 내려갈 수도 있습니다.',
  dailyDone: (d: string) => `${d}의 던전은 10층까지입니다.`,
  compassHint: '가만히 서서 듣기: 출구 방향',
} as const;
