export const S = {
  title: 'ECHO',
  subtitle: '소리로 보는 던전',
  tapToStart: '탭하여 시작',
  normal: '일반 던전',
  daily: '오늘의 던전',
  records: '기록',
  ranking: '랭킹',
  settings: '설정',
  controls: '조작법',
  howTo: '처음이신가요? 어떻게 하나요?',
  resume: '계속',
  toTitle: '타이틀로',
  toTitleConfirm: '진행 중인 탐험이 사라집니다. 타이틀로 돌아갈까요?',
  retry: '다시 도전',
  deeper: '더 깊이',
  close: '닫기',
  next: '다음',
  prev: '이전',
  startNow: '탐험 시작',
  skip: '건너뛰기',
  paused: '일시정지',
  died: '죽었습니다',
  escaped: '탈출 성공!',
  fellAt: (f: number) => `B${f}에서 쓰러졌습니다`,
  floorLabel: (f: number) => `B${f}`,
  locked: '잠겨 있습니다. 열쇠가 필요합니다',
  keyTaken: '열쇠를 찾았습니다! 출구가 열립니다',
  pickup: { stone: '돌멩이 획득 · 1번: 던져서 유인', flare: '조명탄 획득 · 2번: 넓게 밝힘 (시끄러움)', silencer: '소음기 획득 · 3번: 12초 정숙', bandage: '붕대 획득 · 4번: 체력 +1' } as const,
  used: { stone: '돌멩이를 던졌습니다', flare: '조명탄! 주변이 드러납니다. 적도 들었습니다', silencer: '소음기 작동 · 12초', bandage: '붕대 사용 · 체력 +1' } as const,
  itemName: { stone: '돌멩이', flare: '조명탄', silencer: '소음기', bandage: '붕대' } as const,
  itemDesc: {
    stone: '던져서 적을 유인합니다 (마우스 방향)',
    flare: '주변을 넓고 오래 밝힙니다. 매우 시끄럽습니다',
    silencer: '12초 동안 발소리와 펄스 소음이 줄어듭니다',
    bandage: '체력을 1 회복합니다',
  } as const,
  itemFull: '더 들 수 없습니다',
  hpFull: '체력이 가득합니다',
  noItem: { stone: '돌멩이가 없습니다', flare: '조명탄이 없습니다', silencer: '소음기가 없습니다', bandage: '붕대가 없습니다' } as const,
  hit: { hunter: '사냥꾼에게 잡혔습니다!', predator: '포식자의 공격!', spider: '거미 덫을 밟았습니다! 큰 소리가 났습니다', bat: '박쥐' } as const,
  stats: { floor: '도달 층', time: '생존 시간', pulses: '펄스', stones: '던진 돌멩이', damage: '받은 피해', seen: '발견한 적', clear: '클리어 시간' },
  newBest: '최고 기록 갱신',
  newUnlocks: '새 해금',
  deathBy: { hunter: '사냥꾼에게 잡혔습니다', predator: '포식자에게 당했습니다', spider: '거미 덫에 걸렸습니다', bat: '박쥐' } as const,
  tipLabel: '팁',
  tips: [
    'Shift로 살금살금 걸으면 발소리가 거의 나지 않습니다. 적이 가까우면 속도를 줄이세요.',
    '돌멩이를 던지면 사냥꾼이 그쪽을 조사하러 갑니다. 던진 뒤 1초쯤 조용히 있어야 통합니다.',
    '박쥐의 소나는 벽을 공짜로 보여 주지만, 그 소리에 사냥꾼도 몰려옵니다.',
    '심장 소리가 빨라지면 멈춰서 들어 보세요. 붉은 파문이 적의 발소리, 즉 방향입니다.',
    '출구는 3초마다 낮게 웅웅거립니다. 초록 파문이 보이는 쪽으로 가세요.',
    '거미는 방 안에서만 기다립니다. 펄스로 미리 확인하고 돌아가면 안전합니다.',
    '포식자(5층부터)는 큰 소리에 깨어납니다. 조명탄과 덫 소음을 조심하세요.',
    '붕대는 체력이 가득할 때 쓸 수 없습니다. 위험할 때를 위해 아껴 두세요.',
    '펄스는 0.6초마다 쏠 수 있습니다. 하지만 펄스마다 반경 9칸의 적이 듣습니다.',
    '3층부터 출구가 잠깁니다. 열쇠는 4초마다 금색으로 반짝이는 파문을 냅니다.',
  ],
  guide: [
    { title: '소리로 본다', body: '화면은 암흑입니다. Space나 클릭으로 소나 펄스를 쏘면 음파가 닿은 벽만 잠깐 드러났다가 사라집니다. 적, 아이템, 열쇠, 출구도 링이 지나가는 순간 표시됩니다.' },
    { title: '소리는 적을 부른다', body: '펄스, 발소리, 돌멩이, 조명탄은 모두 소음입니다. 사냥꾼(빨간 마름모)은 소리 난 곳을 조사하러 오고, 가까우면 추격합니다. Shift로 살금살금 걸으면 거의 들리지 않습니다.' },
    { title: '적의 소리를 듣는다', body: '적도 소리를 냅니다. 붉은 파문은 사냥꾼의 발소리, 보라색은 박쥐. 화면 위 심장이 빨라지면 적이 가까이 있습니다. 출구는 초록, 열쇠는 금색 파문으로 위치를 알려 줍니다.' },
    { title: '목표', body: '층마다 출구(초록 사각형)를 찾아 내려가세요. 3층부터는 열쇠를 먼저 찾아야 출구가 열립니다. 10층을 탈출하면 승리! 돌멩이(유인)·조명탄·소음기·붕대를 잘 쓰세요.' },
  ],
  floorIntro: {
    findExit: '출구를 찾아 내려가세요',
    findKey: '열쇠를 찾아 출구를 여세요',
    lastFloor: '마지막 층! 출구를 찾으면 탈출입니다',
    endless: '무한 모드 · 얼마나 깊이 갈 수 있을까요',
  },
  objective: { findExit: '목표: 출구 찾기', findKey: '목표: 열쇠 찾기 · 출구 잠김', toExit: '열쇠 획득 · 출구로!', escaping: '탈출 중…' },
  threat: { safe: '안전', caution: '주의', danger: '위험', chase: '추격 중!' },
  pulseReady: '펄스 준비',
  pulseCharging: '재충전',
  firstSeen: {
    hunter: '사냥꾼 발견! 소리를 따라옵니다. 조용히 움직이세요',
    bat: '박쥐 발견. 스스로 소나를 쏩니다 (사냥꾼도 듣습니다)',
    spider: '거미 발견. 밟으면 피해와 큰 소음. 피해서 가세요',
    predator: '포식자 발견… 잠들어 있습니다. 절대 큰 소리를 내지 마세요',
  } as const,
  enemyName: { hunter: '사냥꾼', bat: '박쥐', spider: '거미', predator: '포식자' } as const,
  unlockName: {
    stone_start3: '돌멩이 3개로 시작',
    flare_start: '조명탄 1개로 시작',
    silencer_start: '소음기 1개로 시작',
    compass: '나침반 (가만히 서면 출구 방향)',
    heart4: '하트 4개',
    palette_alt: '호박색 팔레트',
  } as const,
  unlockHint: {
    stone_start3: '3층 도달',
    flare_start: '5층 도달',
    silencer_start: '7층 도달',
    compass: '8층 도달',
    heart4: '10층 클리어',
    palette_alt: '오늘의 던전 5층 도달',
  } as const,
  tutorial: {
    move: 'WASD / 방향키로 이동',
    pulse: 'Space 또는 클릭: 소나 펄스. 벽이 잠깐 보입니다',
    noise: '소리는 적을 부릅니다. Shift로 살금살금',
    stone: '1: 돌멩이를 던져 적을 유인하세요 (마우스 방향)',
    heart: '심장 소리가 빨라지면 적이 가까이 있습니다. 붉은 파문이 방향',
    key: '열쇠를 찾아 출구를 여세요. 금색 파문을 따라가세요',
    listen: '출구는 낮게 웅웅거립니다. 초록 파문을 찾으세요',
    moveTouch: '왼쪽 조이스틱으로 이동',
    pulseTouch: '오른쪽 펄스 버튼: 벽이 잠깐 보입니다',
    noiseTouch: '소리는 적을 부릅니다. 조이스틱을 살짝 밀면 살금살금',
    stoneTouch: '돌멩이 버튼으로 적을 유인하세요',
  },
  settingsLabels: {
    volume: '효과음 볼륨',
    shake: '화면 흔들림',
    touch: '터치 컨트롤',
    palette: '팔레트',
    touchAuto: '자동',
    touchOn: '켬',
    touchOff: '끔',
    paletteDefault: '기본',
    paletteAlt: '호박색',
    nickname: '닉네임 (랭킹)',
    wallMemory: '벽 기억',
    wallMemoryDesc: '한 번 본 벽을 희미하게 남깁니다 (초보자 추천)',
    resetGuide: '가이드·튜토리얼 다시 보기',
    resetGuideDone: '다음 탐험에서 다시 보여 줍니다',
  },
  controlsText: [
    ['이동', 'W A S D / 방향키'],
    ['살금살금', 'Shift (소리 거의 없음, 느림)'],
    ['소나 펄스', 'Space / 마우스 왼쪽'],
    ['돌멩이 던지기', '1 / 마우스 오른쪽 (마우스 방향)'],
    ['조명탄 · 소음기 · 붕대', '2 · 3 · 4'],
    ['일시정지', 'Esc'],
  ],
  legend: [
    ['빨간 마름모', '사냥꾼: 소리를 따라오고 가까우면 추격'],
    ['큰 붉은 마름모', '포식자: 5층부터, 큰 소리에 깨어남'],
    ['보라 날개', '박쥐: 스스로 소나를 쏨'],
    ['연두 별표', '거미 덫: 밟으면 피해 + 큰 소음'],
    ['초록 사각형', '출구 (3초마다 초록 파문)'],
    ['금색 열쇠', '열쇠 (4초마다 금색 파문)'],
    ['하늘색 사각형', '아이템'],
  ],
  recordsLabels: { bestFloor: '최고 층', bestTime: '최단 클리어', runs: '탐험 횟수', dailyList: '오늘의 던전 기록', none: '기록 없음' },
  rank: {
    title: '랭킹',
    floorBoard: '최고 층',
    timeBoard: '최단 탈출',
    dailyBoard: '오늘의 던전',
    loading: '불러오는 중…',
    empty: '아직 기록이 없습니다. 첫 번째가 되어 보세요.',
    offline: '랭킹 서버에 연결할 수 없습니다',
    you: '나',
    submitted: '랭킹에 기록했습니다',
    namePrompt: '랭킹에 표시할 닉네임 (2~12자)',
    nameSave: '저장',
    skip: '건너뛰기',
    rankOf: (r: number) => `${r}위`,
  },
  win: '10층을 돌파해 지상으로 나왔습니다. 더 깊이 내려갈 수도 있습니다.',
  dailyDone: (d: string) => `${d}의 던전은 10층까지입니다.`,
  compassHint: '가만히 서서 듣기: 출구 방향',
} as const;
